### the dataset contains 13 activities among which 4 activities are related to human falls and 9 are normal human activities.

### 3 classes: Fall, Active and Ascension-Descension

#### The fall activities are:
#### FOL: Forward-lying. 
#### FKL: Forward knee-lying. 
#### SDL: Sideward-lying. 
#### BSC: Back sitting chair. 

#### Active:
#### STD: Standing. 
#### WAL: Walking. 
#### JOG: Jogging. 
#### JUM: Jumping.

#### Ascension-Descension:
#### STU: Stairs up. 
#### STN: Stairs down. 
#### SCH: Sit chair. 
#### CSI: Car-step in. 
#### CSO: Car-step out

In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# train data

In [9]:
train = pd.read_csv(r"C:\Users\sattu\Desktop\Ds3\DS3-Project\Train.csv")


In [10]:
train.head()

Unnamed: 0    acc_max   gyro_max  acc_kurtosis  gyro_kurtosis label  \
0         661  26.039919   7.309797     20.378162       2.782476   SDL   
1         122  25.864500   6.511954     14.187190       5.324864   FOL   
2         113  27.524501  12.944099     31.855926      22.891186   FOL   
3          14  30.647705  11.694868     23.608764       9.287735   FOL   
4         529  26.373917  11.168424     14.318453      15.983202   FKL   

     lin_max  acc_skewness  gyro_skewness  post_gyro_max  post_lin_max  fall  
0  11.131080      3.891361       1.592927       7.086618     10.790400     1  
1   7.945561      3.022175       2.376939       6.325522      7.719352     1  
2  14.454818      4.849024       4.283890      12.888111     14.368784     1  
3  15.228303      3.921537       2.794609      11.549971     14.944151     1  
4  10.007396      3.087975       3.363557      11.057636      9.753058     1

## removing column 'fall' and renaming categories :
##  0= fall ;1= active ; 2=ascending descending

In [11]:
train=train.drop('fall',axis=1)

fall=["FOL","FKL","SDL","BSC"]
active=["STD","WAL","JOG","JUM"]
asds=["STU","STN","SCH","CSI","CSO"]

act=[]

for i in range (len(train)):
    if train["label"][i] in fall:
        act.append(0)
    elif train["label"][i] in active:
        act.append(1)
    elif train["label"][i] in asds:
        act.append(2)
train["activity"]=act

train.head()

Unnamed: 0    acc_max   gyro_max  acc_kurtosis  gyro_kurtosis label  \
0         661  26.039919   7.309797     20.378162       2.782476   SDL   
1         122  25.864500   6.511954     14.187190       5.324864   FOL   
2         113  27.524501  12.944099     31.855926      22.891186   FOL   
3          14  30.647705  11.694868     23.608764       9.287735   FOL   
4         529  26.373917  11.168424     14.318453      15.983202   FKL   

     lin_max  acc_skewness  gyro_skewness  post_gyro_max  post_lin_max  \
0  11.131080      3.891361       1.592927       7.086618     10.790400   
1   7.945561      3.022175       2.376939       6.325522      7.719352   
2  14.454818      4.849024       4.283890      12.888111     14.368784   
3  15.228303      3.921537       2.794609      11.549971     14.944151   
4  10.007396      3.087975       3.363557      11.057636      9.753058   

   activity  
0         0  
1         0  
2         0  
3         0  
4         0

In [12]:
#train=train.drop('label',axis=1)
xtrain=train.iloc[:,:-1]
ytrain=train.activity
#print(xtrain)
#print(ytrain)
print(xtrain.shape)


(1428, 11)


In [13]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
xtr=scaler.fit_transform(xtrain)

ValueError: could not convert string to float: 'SDL'

# test data


In [ ]:
test = pd.read_csv("Test.csv")

In [ ]:
test.head()

#    acc_max   gyro_max  acc_kurtosis  gyro_kurtosis label    lin_max  \
0   9  28.055199  10.794617     21.334536      34.163811   FOL  13.880578   
1  11  26.639681   8.785024     13.518671      12.812894   FOL  15.789372   
2  19  25.045219   5.307413     21.603060       4.754182   FOL  11.592445   
3  23  24.102184   8.929061     24.647657      18.595684   FOL  10.107835   
4  28  31.668808  10.714750     18.008912      15.086251   FOL  14.138265   

   acc_skewness  gyro_skewness  post_gyro_max  post_lin_max  fall  
0      3.283404       4.577283      10.755339     13.762561     1  
1      3.301849       3.464729       8.277714     15.341656     1  
2      3.124714       2.268676       4.976134     11.303823     1  
3      4.522305       3.955288       8.719755      9.727437     1  
4      3.142132       3.530621      10.580791     13.935016     1

In [ ]:
test=test.drop('fall',axis=1)

fall=["FOL","FKL","SDL","BSC"]
active=["STD","WAL","JOG","JUM"]
asds=["STU","STN","SCH","CSI","CSO"]

act=[]

for i in range (len(test)):
    if test["label"][i] in fall:
        act.append(0)
    elif test["label"][i] in active:
        act.append(1)
    elif test["label"][i] in asds:
        act.append(2)
test["activity"]=act

test.head()

#    acc_max   gyro_max  acc_kurtosis  gyro_kurtosis label    lin_max  \
0   9  28.055199  10.794617     21.334536      34.163811   FOL  13.880578   
1  11  26.639681   8.785024     13.518671      12.812894   FOL  15.789372   
2  19  25.045219   5.307413     21.603060       4.754182   FOL  11.592445   
3  23  24.102184   8.929061     24.647657      18.595684   FOL  10.107835   
4  28  31.668808  10.714750     18.008912      15.086251   FOL  14.138265   

   acc_skewness  gyro_skewness  post_gyro_max  post_lin_max  activity  
0      3.283404       4.577283      10.755339     13.762561         0  
1      3.301849       3.464729       8.277714     15.341656         0  
2      3.124714       2.268676       4.976134     11.303823         0  
3      4.522305       3.955288       8.719755      9.727437         0  
4      3.142132       3.530621      10.580791     13.935016         0

In [ ]:
test=test.drop('label',axis=1)
xtest=test.iloc[:,:-1]
ytest=test.activity
#print(xtest)
#print(ytest)
print(xtest.shape)


(356, 10)


In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
xts=scaler.fit_transform(xtest)

## knn classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

k=10
classifier=KNeighborsClassifier(n_neighbors=k)
classifier.fit(xtr,ytrain)
pred=classifier.predict(xts)
score1=accuracy_score(ytest,pred)
print("accuracy : ",score1)
c=confusion_matrix(ytest,pred)
print(c)

accuracy :  0.9606741573033708
[[152   0   1]
 [  0  89   0]
 [  3  10 101]]


In [ ]:
res=classifier.predict([xts[87]])
#print(type(res))
if res[0]==0:
    print("person was falling")
elif res[0]==1:
    print('person was active')
elif res[0]==2:
    print('person was ascending descending')

person was falling
